# Generated by Django 4.2.2 on 2023-06-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
