# Generated by Django 4.2.2 on 2023-06-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher'},
        ),
    ]
